import api from './api';
import Papa from 'papaparse';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const getReportData = async (endpoint: string, startDate?: string, endDate?: string) => {
  const params = new URLSearchParams();
  if (startDate) params.append('start_date', startDate);
  if (endDate) params.append('end_date', endDate);
  const response = await api.get(`/api/reports/${endpoint}?${params.toString()}`);
  return response.data;
};

export const getFactorySummaryReport = (s?: string, e?: string) => getReportData('factory-summary', s, e);
export const getAttendanceReport = (s?: string, e?: string) => getReportData('attendance', s, e);
export const getWorkerReport = (s?: string, e?: string) => getReportData('workers', s, e);
export const getProductionReport = (s?: string, e?: string) => getReportData('production', s, e);
export const getMachineReport = (s?: string, e?: string) => getReportData('machines', s, e);
export const getOrderReport = (s?: string, e?: string) => getReportData('orders', s, e);
export const getCustomerReport = (s?: string, e?: string) => getReportData('customers', s, e);

export const exportCSV = (filename: string, data: any[]) => {
  if (!data || data.length === 0) return;
  const csv = Papa.unparse(data);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportPDF = (title: string, summary: any, data: any[], dateRange: string) => {
  const doc = new jsPDF('landscape');
  doc.setFontSize(16);
  doc.text('TEXFLOW - Garment / Textile Factory Management System', 14, 15);
  doc.setFontSize(14);
  doc.text(title, 14, 25);
  doc.setFontSize(10);
  doc.text(`Date Range: ${dateRange}`, 14, 32);
  doc.text(`Generated Date/Time: ${new Date().toLocaleString()}`, 14, 37);
  
  let currentY = 45;
  if (summary && Object.keys(summary).length > 0) {
    doc.setFontSize(12);
    doc.text('Summary', 14, currentY);
    currentY += 6;
    doc.setFontSize(10);
    const summaryEntries = Object.entries(summary);
    
    // Print summary in 2 columns
    for (let i = 0; i < summaryEntries.length; i++) {
        const x = i % 2 === 0 ? 14 : 140;
        doc.text(`${summaryEntries[i][0]}: ${summaryEntries[i][1]}`, x, currentY);
        if (i % 2 !== 0) currentY += 6;
    }
    if (summaryEntries.length % 2 !== 0) currentY += 6;
    currentY += 5;
  }
  
  if (data && data.length > 0) {
    const columns = Object.keys(data[0]);
    const body = data.map(item => columns.map(col => item[col] || '-'));
    autoTable(doc, {
      startY: currentY,
      head: [columns],
      body: body,
      theme: 'grid',
      styles: { fontSize: 8 },
      headStyles: { fillColor: [63, 81, 181] }
    });
  } else {
    doc.text('No records found.', 14, currentY);
  }
  
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text('Generated by TEXFLOW', 14, doc.internal.pageSize.height - 10);
  }
  
  doc.save(`${title.toLowerCase().replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
};
